apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-namespaces
  namespace: openshift-gitops
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: namespace-factory
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}