apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-namespaces
  namespace: openshift-gitops
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: java-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}